# Description: This playbook installs 1Password and the 1Password CLI on Ubuntu
# Based on steps found at https://support.1password.com/install-linux/#other-distributions-or-arm-targz
#
# Example usage against localhost: sudo ansible-playbook ./1password.playbook.yml
# Example usage against remote host: sudo ansible-playbook ./1password.playbook.yml --extra-vars "target_host=[remote host]"

- name: Install 1Password
  hosts: "{{ target_host | default('localhost') }}"
  become: true
  tasks:

    - name: Add the key for the 1Password apt repository
      ansible.builtin.shell: |
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/1password-archive-keyring.gpg

    - name: Add the 1Password apt repository
      ansible.builtin.shell: |
        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | tee /etc/apt/sources.list.d/1password.list
      args:
        creates: /etc/apt/sources.list.d/1password.list

    - name: Create directory for debsig policies
      ansible.builtin.file:
        path: /etc/debsig/policies/AC2D62742012EA22/
        state: directory

    - name: Download 1Password policy file
      ansible.builtin.shell: |
        curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
      args:
        creates: /etc/debsig/policies/AC2D62742012EA22/1password.pol

    - name: Create directory for debsig keyrings
      ansible.builtin.file:
        path: /usr/share/debsig/keyrings/AC2D62742012EA22/
        state: directory

    - name: Download 1Password debsig GPG key
      ansible.builtin.shell: |
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
      args:
        creates: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

    - name: Update APT repository and install 1Password
      ansible.builtin.apt:
        update_cache: yes
        name: 1password
        state: present

    - name: Install 1Password CLI
      ansible.builtin.apt:
        update_cache: no
        name: 1password-cli
        state: present

    - name: Prompt user to configure 1Password CLI
      ansible.builtin.pause:
        prompt: |
          Please configure the 1Password CLI by following these steps:
          1. Ensure you've successfully logged into the 1Password desktop app.
          2. Visit the following link: https://developer.1password.com/docs/cli/get-started/#step-2-turn-on-the-1password-desktop-app-integration
          3. Follow the instructions to enable the Desktop App Integration and test the 1Password CLI tool.
          After completing the setup, press Enter to continue.
