# Description: This playbook installs docker and docker-compose on Ubuntu
#
# Example usage against localhost: sudo ansible-playbook ./docker.playbook.yml
# Example usage against remote host: sudo ansible-playbook ./docker.playbook.yml --extra-vars "target_host=[remote host]"

- name: Install docker
  hosts: "{{ target_host | default('localhost') }}"
  become: true
  tasks:
    - name: Add docker's GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes
    - name: Install docker-compose
      apt:
        name: docker-compose
        state: latest
        update_cache: yes
