# Description: This playbook configures Git with user, email, and configures Github with an SSH key
# Variables:
#   user               local user to have Git configured
#   git_user_name      username for Git user
#   git_user_email     email address for Git user
#   GH_TOKEN           PAT for adding SSH key to Github
#
# Example usage: sudo ansible-playbook ./git.playbook.yml --extra-vars "user=myuser git_user_name=myuser git_user_email=myemail@example.com GH_TOKEN=[token from Github]"

- name: Install Git and configure SSH for Github
  hosts: localhost
  become: yes
  tasks:
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: Create SSH directory
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Delete existing SSH key if it exists
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh/id_rsa"
        state: absent

    - name: Delete existing SSH public key if it exists
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh/id_rsa.pub"
        state: absent

    - name: Generate SSH key
      ansible.builtin.shell: |
        ssh-keygen -t rsa -b 4096 -C "{{ git_user_email }}" -f "/home/{{ user }}/.ssh/id_rsa" -N ""
      args:
        executable: /bin/bash
      become_user: "{{ user }}"
      when: not ansible_check_mode

    - name: Set ownership of key
      ansible.builtin.file:
        path: '/home/{{ user }}/.ssh/id_rsa'
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: '0600'

    - name: Read public SSH key
      ansible.builtin.command:
        cmd: cat /home/{{ user }}/.ssh/id_rsa.pub
      register: public_key_content

    - name: Display public SSH key
      ansible.builtin.debug:
        msg: "{{ public_key_content.stdout_lines[0] }}"

    - name: Configure Git user
      ansible.builtin.git_config:
        name: user.name
        value: "{{ git_user_name }}"

    - name: Configure Git email
      ansible.builtin.git_config:
        name: user.email
        value: "{{ git_user_email }}"

    - name: Upload public SSH key to Github
      ansible.builtin.uri:
        url: https://api.github.com/user/keys
        method: POST
        headers:
          Authorization: "Bearer {{ GH_TOKEN }}"
          Content-Type: "application/json"
        body: |
          {
            "title": "Ansible-generated SSH key for {{ git_user_email }} on {{ ansible_hostname }}",
            "key": "{{ public_key_content.stdout_lines[0] }}"
          }
        body_format: json
        status_code: 201        

    - name: Set Git to use SSH for GitHub
      ansible.builtin.git_config:
        name: url.git@github.com:.insteadOf
        value: "https://github.com/" 
        scope: global

    - name: Add SSH key to ssh-agent
      ansible.builtin.shell: |
        eval "$(ssh-agent -s)"
        ssh-add /home/{{ user }}/.ssh/id_rsa
      args:
        executable: /bin/bash
      become_user: "{{ user }}"
