# Description: This playbook installs Visual Studio Code on Ubuntu
# Variables:
#   none
#
# Example usage against localhost: sudo ansible-playbook ./vscode.playbook.yml
# Example usage against remote host: sudo ansible-playbook ./vscode.playbook.yml -e target_host=[remote host]

- name: Install Visual Studio Code on Ubuntu
  hosts: "{{ target_host | default('localhost') }}"
  roles:
    - ecgalaxy.vscode
